name = "Grincraft 2.1"
author = "Grinner Zone"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87ebe5e9b6e95146da846aa04520744630fc52c90418263ad478a635aa553153"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
