name = "Grincraft 2.1"
author = "Grinner Zone"
version = "2.1.3b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b08e2f62cc894b54b4477fb9834b2a79db4362b813767abc76cda88335cf99a"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
