name = "Grincraft 2.1"
author = "Grinner Zone"
version = "2.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c073c6d00f42419c31d92c632e52a2a8bb80fbe27a1db3e1e6baf804f53f5019"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
